config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :sneakers do
    resources :orders, only: %i[create]
  end
  resources :orders, only: %i[destroy show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :sneaker
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :sneakers, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :contact])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :contact])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def create
    @sneaker = Sneaker.find(params[:sneaker_id])
    @order = Order.new(sneaker: @sneaker, user: current_user)
    @order.save
    redirect_to order_path(@order)
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  before_action :set_sneaker, only: [:show, :edit, :destroy]

  def index
    sneakers = Sneaker.all

    @sneakers = Sneaker.includes(:orders).where(orders: { sneaker_id: nil })

    if params[:brand].present?
      sql_query = "brand ILIKE :query"
      @sneakers = @sneakers.where(sql_query, query: "%#{params[:brand]}%")
    else
      @sneakers
    end
  end

  def show
  end

  def new
    @sneaker = Sneaker.new
  end

  def create
    @sneaker = Sneaker.new(sneaker_params)
    @sneaker.user = current_user
    if @sneaker.save
      redirect_to sneakers_path
    else
      render :new
    end
  end

  def destroy
    @sneaker.destroy
    redirect_to sneakers_path
  end

  private

  def set_sneaker
    @sneaker = Sneaker.find(params[:id])
  end

  def sneaker_params
    params.require(:sneaker).permit( :size, :model, :brand, :condition, :price, :amount, :description, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeSneakers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center container mt-5">
        <div class="card p-3 bg-white center"><i class="fa fa-apple"></i>
             <div class="d-flex justify-content-center mt-0 text-uppercase">
              <h6>Le Sneakers</h6>
             </div>
            <div class="about-product text-center mt-2"><%= image_tag "foto2.jpg", alt: "gengar", width: 400%>
                <div class= "mt-2">
                    <h4>Congratulations!</h4>
                    <h6 class="mt-0 text-black-50">Seu pedido foi aprovado.</h6>
                </div>
            </div>
            <div class="stats mt-4">
                <div class="d-flex justify-content-between p-price "><p><strong>Model:</strong> <%= @order.sneaker.model%></p></div>
                <div class="d-flex justify-content-between p-price"><p><strong>Size:</strong> <%=@order.sneaker.size%></p></div>
                <div class="d-flex justify-content-between p-price"><p><strong>Brand:</strong> <%=@order.sneaker.brand%></p></div>
                <div class="d-flex justify-content-between p-price"><p><strong>Condition:</strong> <%=@order.sneaker.condition%></p></div>
                <div class="d-flex justify-content-between p-price"><p><strong>Amount:</strong> <%=@order.sneaker.amount%></p></div>
            </div>
            <div class="d-flex justify-content-between total font-weight-bold mt-4"><strong>Total</strong> <%= number_to_currency(@order.sneaker.price, unit: "R$", separator: ",", delimiter: "") %></div>

            <%= link_to "Back Home", sneakers_path, class: "btn btn-flat my-3" %>
        </div>
    </div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/lead-the-making-of-the-1-reimagined-nike-news-native-1600-1533854895.jpg?crop=1xw:1xh;center,top&resize=640:*);">
  <div class="container">
    <h1>Come to the world <strong>Sneaker Head!</strong></h1>
    <p> Find your favorite Sneaker!</p>
    <%=link_to "Shop now", sneakers_path, class: "btn btn-flat" %>
  </div>
</div>
<br>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80)">
 <%= link_to "N i k e", sneakers_path(brand: "nike")%>
</div>
<br>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://sneakernews.com/wp-content/uploads/2021/12/adidas-ZX-2K-Boost.jpg)">
 <%= link_to "A d i d a s", sneakers_path(brand: "adidas")%>
</div>
<br>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://publish.one37pm.net/wp-content/uploads/2020/06/bestpumasneakers-hero.jpg?fit=1600%2C707)">
  <%= link_to "P u m a", sneakers_path(brand: "puma")%>
</div>
<br>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://i.pinimg.com/736x/e8/85/db/e885dbc829fcb15c132ae2ff12324138--new-balance-tropical.jpg)">
  <%= link_to "N e w  B a l a n c e", sneakers_path(brand: "newbalance")%>
</div>
<br>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/street-style-gettyimages-646902554-1510693401.jpg?crop=0.601xw:0.677xh;0.179xw,0.237xh&resize=640:*)">
  <%= link_to "V a n s", sneakers_path(brand: "vans")%>
</div>


<br>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Development by YOLO® 2022. All rights reserved ©.
  </div>
</div>

app/views/pages/order.html.erb
<h1>To bay</h1>

app/views/pages/sneaker.html.erb
<h1>Sneaker all</h1>

app/views/pages/user.html.erb
<h1>User</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/2589/2589903.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%#= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%#= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "logofinal.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%#= link_to "Action", "#", class: "dropdown-item" %>
              <%#= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/sneakers/index.html.erb
    <div class="container my-5 sneaker-container">
    <h2>SNEAKERS</h2>
    <h3><%= link_to "New sneaker", new_sneaker_path, class:"btn btn-flat" %></h3>
      <div class="sneakers-grid">
        <% @sneakers.each do |sneaker| %>
          <div>
            <div class="card my-4" style="width: 18rem;">
              <% if sneaker.photos.attached? %>
                <%= cl_image_tag sneaker.photos.first.key, crop: :fill, class: "sneaker-image" %>
              <% end %>
              <div class="card-body">
                <h6 class="card-title"><strong>Model:</strong> <%= sneaker.model %></h6>
                <h6 class="card-title"><strong>Price:</strong> <%= number_to_currency(sneaker.price, unit: "R$", separator: ",", delimiter: "") %></h6>
                <p><%= link_to "Details", sneaker_path(sneaker), class:"text-decoration-none btn btn-flat" %>
              </div>
            </div>
          </div>
        <% end %>
        </div>
      </div>

app/views/sneakers/new.html.erb
  <div class="container form-inputs my-5">
    <div container class= >
      <h2>Add new sneaker</h2>
    </div>
        <%= simple_form_for @sneaker do |f| %>
          <div class= row>
              <div class="col">
                <%= f.input :size, placeholder: 'Size' %>
              </div>
              <div class="col">
                <%= f.input :model, placeholder: 'Model' %>
              </div>
          </div>
          <div class= row>
            <div class="col">
              <%= f.input :brand, placeholder: 'Brand' %>
            </div>
            <div class="col">
              <%= f.input :condition, placeholder: 'Condition' %>
            </div>
          </div>
          <div class= row>
            <div class="col">
              <%= f.input :price, placeholder: 'Price' %>
            </div>
            <div class="col">
              <%= f.input :amount, placeholder: 'Amount' %>
            </div>
          </div>
          <%= f.input :description, placeholder: 'Description' %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit class: 'btn btn-flat' %>
          <%=link_to "Back", sneakers_path, class: "text-decoration-none card-body"%>

        <% end %>
  </div>

app/views/sneakers/show.html.erb
  <div class="row">
    <div class="col-6">
      <% if @sneaker.photos.attached? %>
        <div id="sneaker-carousel" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <% @sneaker.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= 'active' if index.zero? %>">
                <%= cl_image_tag photo.key, height: 300, width: 500, crop: :fill, class: "d-block w-100" %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#sneaker-carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#sneaker-carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      <% end %>
    </div>

    <div class="col-6">
      <h2> Model: <%=@sneaker.model%></h2>
      <p><strong> Size: </strong><%=@sneaker.size%></p>
      <p><strong> Brand: </strong><%=@sneaker.brand%></p>
      <p><strong> Condition: </strong> <%=@sneaker.condition%></p>
      <p><strong> Description: </strong><%=@sneaker.description%></p>
      <p><strong> Amount: </strong><%=@sneaker.amount%></p>
      <div class="d-flex justify-content-evenly align-items-center">
        <% if @sneaker.user == current_user %>
          <%= link_to "Delete", sneaker_path(@sneaker), method: :delete,  data: { confirm: 'Are you sure you want delete?' }, class:'btn btn-flat'%>
        <% else %>
          <%= link_to "Buy", sneaker_orders_path(@sneaker), method: :post, data: { confirm: 'Are you sure you want to buy?' }, class:'btn btn-flat'%>
        <% end %>
        <div class="card-body">
          <%= link_to "Back", sneakers_path%>
        </div>
      </div>
    </div>